services:
  tkredis:
    image: redis:latest
    container_name: tkredis
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    restart: always

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - '5540:5540'
    environment:
      - REDISINSIGHT_HOST=0.0.0.0
      - REDISINSIGHT_PORT=5540
    depends_on:
      - tkredis
    restart: always
